baseUrl = "https://peromage.github.io"
title = "(->> love life knowledge (seek))"
paginate = 20

disqusShortname = ""
googleAnalytics = ""

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[author]
name = "Fang Deng"
