baseUrl = "https://peromage.github.io"
title = "Fang's Blog"
paginate = 20

disqusShortname = "peromage"
googleAnalytics = ""

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[author]
name = "Fang Deng"
