[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[main.params]
icon = "home"
newTab = false

[[main]]
identifier = "about"
name  = "About"
url = "/about"
weight = -80
[main.params]
icon = "user"
newTab = false

[[main]]
identifier = "search"
name  = "Search"
url = "/search"
weight = -70
[main.params]
icon = "search"
newTab = false
