baseUrl = "https://peromage.github.io"
title = "Fang's Blog"
paginate = 20

disqusShortname = "peromage"
googleAnalytics = ""

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[permalinks]
blog = "/p/:slug/"
page = "/:slug/"

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[taxonomies]
category = "categories"
tag = "tags"
