# -*- yaml-indent-offset: 2; -*-

name: Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 28.1

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Check out blog source
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Deploy with Hugo
        run: ./deploy.sh

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo/public
          publish_branch: pages  # default: gh-pages
